name: check_code_quality
on: pull_request
jobs:
  code_quality:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install black pylint isort
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Black
        run: |
          black --check --verbose .
      - name: Run Pylint
        run: |
          pylint *.py
      - name: Run isort
        run: |
          isort --check-only --diff .